export const DRONE_GET_ALL_DRONE_REQUEST = 'DRONE_GET_ALL_DRONE_REQUEST';
export const DRONE_GET_ALL_DRONE_SUCCESS = 'DRONE_GET_ALL_DRONE_SUCCESS';
export const DRONE_GET_ALL_DRONE_FAIL = 'DRONE_GET_ALL_DRONE_FAIL';

export const DRONE_GET_DRONE_FROM_ID_REQUEST = 'DRONE_GET_DRONE_FROM_ID_REQUEST';
export const DRONE_GET_DRONE_FROM_ID_SUCCESS = 'DRONE_GET_DRONE_FROM_ID_SUCCESS';
export const DRONE_GET_DRONE_FROM_ID_FAIL = 'DRONE_GET_DRONE_FROM_ID_FAIL';

export const DRONE_CREATE_DRONE_REQUEST = 'DRONE_CREATE_DRONE_REQUEST';
export const DRONE_CREATE_DRONE_SUCCESS = 'DRONE_CREATE_DRONE_SUCCESS';
export const DRONE_CREATE_DRONE_FAIL = 'DRONE_CREATE_DRONE_FAIL';

export const DRONE_UPDATE_DRONE_FROM_ID_REQUEST = 'DRONE_UPDATE_DRONE_FROM_ID_REQUEST';
export const DRONE_UPDATE_DRONE_FROM_ID_SUCCESS = 'DRONE_UPDATE_DRONE_FROM_ID_SUCCESS';
export const DRONE_UPDATE_DRONE_FROM_ID_FAIL = 'DRONE_UPDATE_DRONE_FROM_ID_FAIL';

export const DRONE_DELETE_DRONE_FROM_ID_REQUEST = 'DRONE_DELETE_DRONE_FROM_ID_REQUEST';
export const DRONE_DELETE_DRONE_FROM_ID_SUCCESS = 'DRONE_DELETE_DRONE_FROM_ID_SUCCESS';
export const DRONE_DELETE_DRONE_FROM_ID_FAIL = 'DRONE_DELETE_DRONE_FROM_ID_FAIL';