// ===============================Get Product==================================
export const PRODUCT_GET_8_TOP_PRODUCT_REQUEST = 'PRODUCT_GET_8_TOP_PRODUCT_REQUEST';
export const PRODUCT_GET_8_TOP_PRODUCT_SUCCESS = 'PRODUCT_GET_8_TOP_PRODUCT_SUCCESS';
export const PRODUCT_GET_8_TOP_PRODUCT_FAIL = 'PRODUCT_GET_8_TOP_PRODUCT_FAIL';

export const PRODUCT_GET_8_NEW_PRODUCT_REQUEST = 'PRODUCT_GET_8_NEW_PRODUCT_REQUEST';
export const PRODUCT_GET_8_NEW_PRODUCT_SUCCESS = 'PRODUCT_GET_8_NEW_PRODUCT_SUCCESS';
export const PRODUCT_GET_8_NEW_PRODUCT_FAIL = 'PRODUCT_GET_8_NEW_PRODUCT_FAIL';

export const PRODUCT_GET_8_PRODUCT_RELATIVE_REQUEST = 'PRODUCT_GET_8_PRODUCT_RELATIVE_REQUEST';
export const PRODUCT_GET_8_PRODUCT_RELATIVE_SUCCESS = 'PRODUCT_GET_8_PRODUCT_RELATIVE_SUCCESS';
export const PRODUCT_GET_8_PRODUCT_RELATIVE_FAIL = 'PRODUCT_GET_8_PRODUCT_RELATIVE_FAIL';

export const PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_REQUEST = 'PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_REQUEST';
export const PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_SUCCESS = 'PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_SUCCESS';
export const PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_FAIL = 'PRODUCT_GET_PRODUCT_FROM_TYPEPRODUCT_FAIL';

export const PRODUCT_GET_PRODUCT_FROM_ID_REQUEST = 'PRODUCT_GET_PRODUCT_FROM_ID_REQUEST';
export const PRODUCT_GET_PRODUCT_FROM_ID_SUCCESS = 'PRODUCT_GET_PRODUCT_FROM_ID_SUCCESS';
export const PRODUCT_GET_PRODUCT_FROM_ID_FAIL = 'PRODUCT_GET_PRODUCT_FROM_ID_FAIL';

export const PRODUCT_GET_PRODUCT_FROM_SEARCH_REQUEST = 'PRODUCT_GET_PRODUCT_FROM_SEARCH_REQUEST';
export const PRODUCT_GET_PRODUCT_FROM_SEARCH_SUCCESS = 'PRODUCT_GET_PRODUCT_FROM_SEARCH_SUCCESS';
export const PRODUCT_GET_PRODUCT_FROM_SEARCH_FAIL = 'PRODUCT_GET_PRODUCT_FROM_SEARCH_FAIL';

// ===============================Product Admin==================================
export const PRODUCT_GET_ALL_REQUEST = 'PRODUCT_GET_ALL_REQUEST';
export const PRODUCT_GET_ALL_SUCCESS = 'PRODUCT_GET_ALL_SUCCESS';
export const PRODUCT_GET_ALL_FAIL = 'PRODUCT_GET_ALL_FAIL';

export const PRODUCT_CREATE_PRODUCT_REQUEST = 'PRODUCT_CREATE_PRODUCT_REQUEST';
export const PRODUCT_CREATE_PRODUCT_SUCCESS = 'PRODUCT_CREATE_PRODUCT_SUCCESS';
export const PRODUCT_CREATE_PRODUCT_FAIL = 'PRODUCT_CREATE_PRODUCT_FAIL';

export const PRODUCT_UPDATE_PRODUCT_FROM_ID_REQUEST = 'PRODUCT_UPDATE_PRODUCT_FROM_ID_REQUEST';
export const PRODUCT_UPDATE_PRODUCT_FROM_ID_SUCCESS = 'PRODUCT_UPDATE_PRODUCT_FROM_ID_SUCCESS';
export const PRODUCT_UPDATE_PRODUCT_FROM_ID_FAIL = 'PRODUCT_UPDATE_PRODUCT_FROM_ID_FAIL';

export const PRODUCT_DELETE_PRODUCT_FROM_ID_REQUEST = 'PRODUCT_DELETE_PRODUCT_FROM_ID_REQUEST';
export const PRODUCT_DELETE_PRODUCT_FROM_ID_SUCCESS = 'PRODUCT_DELETE_PRODUCT_FROM_ID_SUCCESS';
export const PRODUCT_DELETE_PRODUCT_FROM_ID_FAIL = 'PRODUCT_DELETE_PRODUCT_FROM_ID_FAIL';
