export const  TYPEPRODUCT_GET_ALL_TYPEPRODUCT_REQUEST = ' TYPEPRODUCT_GET_ALL_TYPEPRODUCT_REQUEST';
export const  TYPEPRODUCT_GET_ALL_TYPEPRODUCT_SUCCESS = ' TYPEPRODUCT_GET_ALL_TYPEPRODUCT_SUCCESS';
export const  TYPEPRODUCT_GET_ALL_TYPEPRODUCT_FAIL = 'TYPEPRODUCT_GET_ALL_TYPEPRODUCT_FAIL';

export const  TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_REQUEST = ' TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_REQUEST';
export const  TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_SUCCESS = ' TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_SUCCESS';
export const  TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_FAIL = 'TYPEPRODUCT_GET_TYPEPRODUCT_FROM_ID_FAIL';

export const  TYPEPRODUCT_CREATE_TYPEPRODUCT_REQUEST = ' TYPEPRODUCT_CREATE_TYPEPRODUCT_REQUEST';
export const  TYPEPRODUCT_CREATE_TYPEPRODUCT_SUCCESS = ' TYPEPRODUCT_CREATE_TYPEPRODUCT_SUCCESS';
export const  TYPEPRODUCT_CREATE_TYPEPRODUCT_FAIL = 'TYPEPRODUCT_CREATE_TYPEPRODUCT_FAIL';

export const  TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_REQUEST = 'TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_REQUEST';
export const  TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_SUCCESS = 'TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_SUCCESS';
export const  TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_FAIL = 'TYPEPRODUCT_UPDATE_TYPEPRODUCT_FROM_ID_FAIL';

export const  TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_REQUEST = ' TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_REQUEST';
export const  TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_SUCCESS = ' TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_SUCCESS';
export const  TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_FAIL = 'TYPEPRODUCT_DELETE_TYPEPRODUCT_FROM_ID_FAIL';