// ===============================Đăng xuất, đăng nhập==================================
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

// ===============================User Admin==================================
export const USER_GET_ALL_USER_REQUEST = 'USER_GET_ALL_USER_REQUEST';
export const USER_GET_ALL_USER_SUCCESS = 'USER_GET_ALL_USER_SUCCESS';
export const USER_GET_ALL_USER_FAIL = 'USER_GET_ALL_USER_FAIL';

export const USER_GET_USER_FROM_TOKEN_REQUEST = 'USER_GET_USER_FROM_TOKEN_REQUEST';
export const USER_GET_USER_FROM_TOKEN_SUCCESS = 'USER_GET_USER_FROM_TOKEN_SUCCESS';
export const USER_GET_USER_FROM_TOKEN_FAIL = 'USER_GET_USER_FROM_TOKEN_FAIL';

export const USER_UPDATE_USER_FROM_ID_REQUEST = 'USER_UPDATE_USER_FROM_ID_REQUEST';
export const USER_UPDATE_USER_FROM_ID_SUCCESS = 'USER_UPDATE_USER_FROM_ID_SUCCESS';
export const USER_UPDATE_USER_FROM_ID_FAIL = 'USER_UPDATE_USER_FROM_ID_FAIL';

export const USER_DELETE_USER_FROM_ID_REQUEST = 'USER_DELETE_USER_FROM_ID_REQUEST';
export const USER_DELETE_USER_FROM_ID_SUCCESS = 'USER_DELETE_USER_FROM_ID_SUCCESS';
export const USER_DELETE_USER_FROM_ID_FAIL = 'USER_DELETE_USER_FROM_ID_FAIL';


